import type { Metadata } from "next";
import { Roboto_Condensed, Inter } from "next/font/google";
import "./globals.css";
import InfoCardPopup from "@/components/info-card";

const robotoCondensed = Roboto_Condensed({
    weight: "700",
    subsets: ["latin"],
    variable: "--heading-font",
});

const inter = Inter({
    weight: ["400", "500", "600", "800"],
    subsets: ["latin"],
    variable: "--subheading-font",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${robotoCondensed.variable} ${inter.variable} antialiased relative`}>
                {children}
                <InfoCardPopup />
            </body>
        </html>
    );
}
